window.onload=function(){
	document.getElementById("product").mouseover(function(){
		document.getElementById("sub1").style.visibility="visible";
	});
	document.getElementById("product").mouseout(function(){
		document.getElementById("sub1").style.visibility="hidden";
	})
	document.getElementById("support").mouseover(function(){
		document.getElementById("sub2").style.visibility="visible";
	});
	document.getElementById("support").mouseout(function(){
		document.getElementById("sub2").style.visibility="hidden";
	})
	document.getElementById("about").mouseover(function(){
		document.getElementById("sub3").style.visibility="visible";
	});
	document.getElementById("about").mouseout(function(){
		document.getElementById("sub3").style.visibility="hidden";
	})
	
}
